### ISSUE TITLE
Searching for boring tool

### ISSUE THREAD

**Issue by shohei** [nakujaproject/N3-launch-preparation#1]

**Comment by halaisameel** [comment]
We received a quote of KSH 38,000 + VAT for the boring tool. The dimensions of the tool we found, including attachable extension was 12 inch length (30cm) and tool diameter of 1inch (2.5cm). The cutting tip is replaceable and costs 4,500 for replacement. Nephat should be able to share the photos of the tool we found.

**Comment by NGGithua1** [comment]
Procurement of boring tool 12inch (India ISO-9 Boring & Facing Bar 25 x 25) already done.
